name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Checkout Dependecies
      run: |
        git clone https://github.com/bucanero/dbglogger.git       --depth 1
        git clone https://github.com/bucanero/ps3mapi-lib.git     --depth 1

    - name: Set env vars
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "pkg_file=ArtemisPS3-GUI/ArtemisPS3-GUI.pkg" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xvz -C ./
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV


    - name: Install Python 2.7
      run: |
        echo "Configurando dependências legadas: OpenSSL 1.1 e Python 2.7..."
        echo 'deb http://archive.ubuntu.com/ubuntu focal main universe' | sudo tee -a /etc/apt/sources.list
        echo 'deb http://security.ubuntu.com/ubuntu focal-security main universe' | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y python2 || true
        sudo ln -sf /usr/bin/python2 /usr/bin/python2.7


    
    - name: Install OpenSSL 1.1 Runtime
      run: |
        echo "Instalando dependências legacy do OpenSSL 1.1..."
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb -O libssl1.1.deb
        sudo dpkg -i libssl1.1.deb
        

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make
        make install

    - name: Install ps3mapi-lib
      working-directory: ps3mapi-lib
      run: |
        make
        make install

    - name: Build Artemis App Package
      working-directory: ArtemisPS3-GUI
      run: |
        make createzip
        make pkg

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: artemis-ps3-build_${{ steps.slug.outputs.sha8 }}
        path: ${{ env.pkg_file }}
        if-no-files-found: error
